### ISSUE TITLE
Informar segurança da senha nos termos de uso

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/legislaqui#169]
- [ ] Senha é segura
- [ ] Não entregamos dados dos nossos usuários para ninguém
- [ ] Explicar que a senha específica é só para o acesso aos sistema. Ex.: Crie uma senha para acessar este sistema.
- [ ] DCS precisa nos ajudar a escrever esses textos

**Comment by coelhoandre89** [comment]
Ok, incluído nos termos de uso: https://docs.google.com/document/d/1hW59fQKlNO0i84LQZ8M7HfSvWviXqsEhix421EdWWP4/edit?usp=sharing

**Comment by BMasquio** [comment]
Está nos termos de uso.
