### ISSUE TITLE
Alterar títulos 

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/legislaqui#170]
- [x] "na Comissão" vira "em aprovação"
- [x]  "de aprovadas" vira "em tramitação"
- [x] Procurar na aplicação toda, inclusive no admin

**Comment by BMasquio** [comment]
É relativo às ideias legislativos? Seria tipo isso aqui?
![image](https://user-images.githubusercontent.com/15174854/60672476-d2ed1780-9e4b-11e9-95a7-9a8b7f8652b2.png)

**Comment by antonioribeiro** [comment]
Isso, mas já fiz, valeu!
