### ISSUE TITLE
Enviar notificações sempre que uma lei for modificada

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/legislaqui#181]
- [ ] Para o criador da lei
- [ ] Para todos os que assinaram o "ACOMPANHAR ESSA IDEIA!"

**Comment by BMasquio** [comment]
Fazendo

**Comment by antonioribeiro** [comment]
Chegou a terminar isso?

**Comment by BMasquio** [comment]
Não terminei ainda

**Comment by BMasquio** [comment]
Atualizei a issue

#361
