### ISSUE TITLE
Vamos classificar as Ideias?

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/legislaqui#182]
**Lista de tipos do e-Cidadania**

Administrativo
Econômico
Jurídico
Social
Honorífico
Administração pública: órgãos públicos
Licitação e contratos
Militares dos estados, DF e territórios
Organização político-administrativa do Estado
Servidores públicos
Agricultura, pecuária e abastecimento
Desenvolvimento regional
Fiscalização e controle
Indústria e comércio
Planejamento e orçamento
Minas e energia
Recursos hídricos
Pesca e agricultura
Política econômica e sistema financeiro
Política fundiária e reforma agrária
Política urbana
Tributação
Turismo
Viação e transportes
Zona de processamento de exportação
Data comemorativa
Homenagem cívica
Defesa do consumidor
Defesa nacional e forcas armadas
Direito aeronáutico e direito espacial
Direito civil e processual civil
Direito comercial e econômico
Direito eleitoral e partidos políticos
Direito marítimo
Direito penal e processual penal
Direito dos estrangeiros
Direitos políticos, nacionalidade e cidadania
Processo legislativo
Relações internacionais
Segurança pública
Trânsito
Arte e cultura
Assistência social
Ciência, tecnologia e informática
Comunicações
Desporto e lazer
Desenvolvimento social e combate a fome
Direitos humanos e minorias
Educação
Família, proteção a crianças, adolescentes, mulheres e idosos
Meio ambiente
Previdência social
Trabalho e emprego
Saúde

**Comment by antonioribeiro** [comment]
@coelhoandre89, precisamos decidir se vamos seguir com esse caminho

**Comment by BMasquio** [comment]
Implementamos isso, o Aldir pediu para tirar e tiramos.
