### ISSUE TITLE
Erro ao logar na versão nova

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/legislaqui#183]
@BMasquio, todas as tuas mudanças estão gravadas no Github?

![image](https://user-images.githubusercontent.com/3182864/60209638-6d889d80-9831-11e9-814d-bef2c05ce0f1.png)

**Comment by antonioribeiro** [comment]
@brenot, ping

**Comment by BMasquio** [comment]
https://github.com/alerj/legislaqui/pull/184

Pode ser isso aqui. Aceitando esse pull request, está tudo igual ao meu.

**Comment by BMasquio** [comment]
Já foi consertado isso
