### ISSUE TITLE
Página de abertura

### ISSUE THREAD

**Issue by antonioribeiro** [alerj/legislaqui#189]
Deverá conter links (botões ou imagens) para:

- [ ] Ideias Legislativas
- [ ] Acompanhamento das audiências das Comissões
- [ ] Wikilegis (https://edemocracia.camara.leg.br/wikilegis/)

**Comment by BMasquio** [comment]
Não entendi onde seria isso

**Comment by BMasquio** [comment]
Não vamos fazer isso por enquanto. Não vai ter a referência ao wikilegis nem ao audiências interativas
