### ISSUE TITLE
Revisar a situação das ideias 

### ISSUE THREAD

**Issue by ricardocamargo07** [alerj/legislaqui#200]
![print](https://user-images.githubusercontent.com/53793788/63616728-8f4a9a80-c5be-11e9-81e5-748fcabfe8a7.png)

Ao apertar em "EM APROVAÇÃO", "ESPIRADAS", "NÃO ACATADAS" e "EM TRAMITAÇÃO" o site redireciona mas  no final acaba voltando para a situação "ABERTAS". Não indo para o lugar solicitado.

**Comment by BMasquio** [comment]
Testei e parece estar resolvido.
