### ISSUE TITLE
Revisar recebimento de email cópia

### ISSUE THREAD

**Issue by ricardocamargo07** [alerj/legislaqui#201]
![print](https://user-images.githubusercontent.com/53793788/63618335-2fee8980-c5c2-11e9-80ea-82a34360a02a.png)

Não recebi nenhum tipo de email cópia no teste que realizei.

**Comment by BMasquio** [comment]
Este módulo não está funcionando. Tem que implementar.

**Comment by BMasquio** [comment]
- [ ] Criar a view do e-mail com a mensagem (O Breno depois vai fazer o design)

- [ ] Enviar o e-mail para uma conta de suporte referenciada no .env e no config contendo os dados do remetente do form

- [ ] Enviar a cópia do e-mail para o remetente com a mensagem

**Comment by BMasquio** [comment]
Relacionando: #222

**Comment by BMasquio** [comment]
Feito
