### ISSUE TITLE
Problema ao criar Ideia Legislativa

### ISSUE THREAD

**Issue by brenot** [alerj/legislaqui#203]
Ao tentar criar uma ideia o sistema retorna mensagem de erro

![Screen Shot 2020-07-15 at 12 05 00](https://user-images.githubusercontent.com/1885417/87563558-c2de5980-c695-11ea-8ea8-26fb352cc1f1.png)

**Comment by BMasquio** [comment]
Vc deixou o campo idea_central como nulo e não há validação pra isso. Tem que colocar.
