### ISSUE TITLE
Reposta da moderação talvez não esteja sendo salva

### ISSUE THREAD

**Issue by BMasquio** [alerj/legislaqui#208]
![image](https://user-images.githubusercontent.com/15174854/87811487-25219080-c835-11ea-8c82-c386353b489a.png)

**Comment by ffmatheus** [comment]
![image](https://user-images.githubusercontent.com/55103202/88079850-a25e4580-cb54-11ea-8533-01a9bea55ef0.png)

Analisando o código, percebi que a resposta somente é salva em caso de desaprovação, como pode ser visto na imagem anexada.
Talvez a estrutura tenha sido feita considerando que somente é necessária uma resposta , como uma espécie de feedback , em caso de não aceitação da proposta.

**Comment by ffmatheus** [comment]
![image](https://user-images.githubusercontent.com/55103202/88080340-5069ef80-cb55-11ea-9c6f-5e98241ea96d.png)

Confirmando a atualização anterior, o código foi feito para salvar a resposta somente se o botão Desaprovar for acionado.

**Comment by BMasquio** [comment]
É isso mesmo
