### ISSUE TITLE
Validação no front end duplicada

### ISSUE THREAD

**Issue by BMasquio** [alerj/legislaqui#209]
![image](https://user-images.githubusercontent.com/15174854/87813907-2c4a9d80-c839-11ea-9fc6-1d02f9e096ea.png)

**Comment by ffmatheus** [comment]
![image](https://user-images.githubusercontent.com/55103202/88322857-b5f5e180-ccf7-11ea-805b-5558a67443c6.png)

![image](https://user-images.githubusercontent.com/55103202/88322888-c017e000-ccf7-11ea-8cbf-eee166cfb984.png)

Analisando o código, acredita-se que a validação está sendo feita tanto fora, quanto dentro do formulário.

**Comment by ffmatheus** [comment]
![image](https://user-images.githubusercontent.com/55103202/88323008-ed648e00-ccf7-11ea-9fd5-a074e78ed421.png)

Removendo a primeira validação a duplicação foi removida. Vou subir o Pull Resquest com a atualização.

**Comment by BMasquio** [comment]
Feito
