### ISSUE TITLE
Dúvida sobre projetos aprovados

### ISSUE THREAD

**Issue by RobsonMacedo** [alerj/legislaqui#215]
Os projetos que foram aprovados e possuem os votos necessários serão necessariamente encaminhados para projeto de lei????
Existe alguma analise posterior????

**Comment by orlandovinicius1987** [comment]
Pelo que eu entendi, eles ficam disponíveis para a comissão apreciar, mas melhor perguntar pra Alyne

**Comment by BMasquio** [comment]
Perguntei a Alyne. A comissão é obrigada a criar o projeto de lei. O máximo que pode acontecer é isso demorar
