### ISSUE TITLE
Revisar a paginação

### ISSUE THREAD

**Issue by ricardocamargo07** [alerj/legislaqui#240]
![Screen Shot 2020-08-21 at 14 50 00](https://user-images.githubusercontent.com/53793788/90920461-b5b43900-e3be-11ea-976e-df5f3ee6686f.png)

Paginação só funciona até a 4ª página ocultando parte das Ideias Legislativas.

**Comment by orlandovinicius1987** [comment]
Não consegui reproduzir o erro nessa versão atual do software
