### ISSUE TITLE
Trocar exibição das ideias de tabelas para cards

### ISSUE THREAD

**Issue by BMasquio** [alerj/legislaqui#241]
- Ao invés dessa tabela com linhas das ideias:

![image](https://user-images.githubusercontent.com/15174854/91206100-fb357680-e6dc-11ea-834c-d4c1518bd4da.png)

- Colocar algo assim:
https://getbootstrap.com/docs/4.5/components/card/#titles-text-and-links
![image](https://user-images.githubusercontent.com/15174854/91206070-ea850080-e6dc-11ea-8cf7-bd5ece66b41d.png)

**Comment by brenot** [comment]
essa nao foi nao?

**Comment by BMasquio** [comment]
Feito
