### ISSUE TITLE
Acertar o case e tirar acento de "ideia"

### ISSUE THREAD

**Issue by BMasquio** [alerj/legislaqui#317]
- Padronizar o case. Usar ou **title case** ou **sentence case** . Consultar https://convertcase.net/

- Ideia não tem mais acento => https://www.estrategiaconcursos.com.br/blog/novo-acordo-ortografico-ideia-ou-ideia/#:~:text=N%C3%A3o%2C%20ideia%20n%C3%A3o%20tem%20acento.&text=A%20grafia%20%E2%80%9Cid%C3%A9ia%E2%80%9D%20(com,%E2%80%9D%2C%20%E2%80%9Cb%C3%B3ia%E2%80%9D%20etc.

![image](https://user-images.githubusercontent.com/15174854/99106725-75321900-25c3-11eb-9778-a024ce526213.png)

**Comment by brenot** [comment]
feito

**Comment by BMasquio** [comment]
Cadê o Pull Request?

**Comment by BMasquio** [comment]
Ainda não está na mesma case do "Ideia Legislativa"

![image](https://user-images.githubusercontent.com/15174854/99968812-67755400-2d78-11eb-8c81-b44f894f025e.png)

**Comment by brenot** [comment]
feito
