### ISSUE TITLE
Dois links para o cidadão buscar se a norma já existe

### ISSUE THREAD

**Issue by BMasquio** [alerj/legislaqui#319]
Junto com o texto na página inicial, colocar uma mensagem para que o cidadão pesquise se a norma já existe em tramitação ou em vigência.

- Lei
    - http://www3.alerj.rj.gov.br/lotus_notes/default.asp?id=55
- Projeto de lei tramitando
    - http://www3.alerj.rj.gov.br/lotus_notes/default.asp?id=144

**Comment by brenot** [comment]
Feito

**Comment by BMasquio** [comment]
Cadê o Pull Request?

**Comment by BMasquio** [comment]
Feito
