### ISSUE TITLE
Falta de filtros - Admin

### ISSUE THREAD

**Issue by ricardocamargo07** [alerj/legislaqui#441]
http://legislaqui.test/admin/proposals/approved

Filtros:

- Mostrando: ** registros

- Pesquisa:
![a72cf4d9-a826-46c5-9dc5-afc00d8941e9](https://user-images.githubusercontent.com/53793788/102121914-7acd8980-3e23-11eb-9590-c7fc28ba8749.jpg)

**Comment by BMasquio** [comment]
Feito
